name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile  # Adjust the path if your Dockerfile is in a different directory
          container-name: wltmlx/postgres-docker-gcs-backup  

      - name: Build Docker image
        run: docker build -t wltmlx/postgres-docker-gcs-backup .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push wltmlx/postgres-docker-gcs-backup
